/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oteljava.example;

import io.opentelemetry.api.OpenTelemetry;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.setProperty("otel.resource.attributes", "service.name=OtlpExporterExample");
        // it is important to initialize your SDK as early as possible in your application's lifecycle
        OpenTelemetry openTelemetry = Configuration.initOpenTelemetry();
        System.out.println(new App().getGreeting());
    }
}
