/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
    implementation("io.opentelemetry:opentelemetry-api:1.6.0")
    implementation("io.opentelemetry:opentelemetry-sdk:1.6.0")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp:1.6.0")

    //pull in the autoconfigure extension so we parse the `otel.resource.attributes` system property used in the example.
    implementation("io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:1.6.0-alpha")

    //external dependency for the grpc transport implementation
    implementation("io.grpc:grpc-netty-shaded:1.41.0")
}

application {
    // Define the main class for the application.
    mainClass.set("oteljava.example.App")
}
